window.TRIP_DATA = {
  trip: {
    title: "Đà Lạt tháng 07/2026",
    subtitle: "Lịch trình chuyến đi",
    destination: "Đà Lạt",
    startDate: "2026-07-03",
    endDate: "2026-07-05",
    timezone: "Asia/Ho_Chi_Minh",
    currency: "VND",
    travelers: ["Gia đình Long - Oanh, Hải - Hiền"],
    departure_point: "Phú Mỹ, BRVT",
    coverImage: "",
    hotel: {
      name: "Best Western Premier Imperial Hotel Dalat",
      address: "2-4 Đường Trần Phú, Phường 3, Thành phố Đà Lạt, Lâm Đồng",
      coords: [11.9348, 108.4385],
      icon: "fa-hotel",
      checkin: "03/07",
      checkout: "05/07",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat"
    },
    transportation: {
      departure: "Xe cá nhân xuất phát từ Phú Mỹ, BRVT lúc 05:30 ngày 03/07/2026",
      local: "Xe cá nhân",
      airportTransfer: "Không sử dụng"
    }
  },

  days: [
    {
      day: 1,
      title: "Hành trình lên Cao Nguyên",
      themeColor: "#2563eb",
      date: "2026-07-03",
      summary: "Di chuyển qua tuyến cao tốc, nghỉ ngơi tại Trạm dừng chân TTC Phan Thiết - Vĩnh Hảo, ăn trưa Chuồn Chuồn Bistro, nhận phòng khách sạn, ăn tối cơm lam gà nướng và chill cà phê Horizon.",
      center: [11.5500, 108.1000],
      zoom: 10,
      weather: "Mát mẻ, có thể có mưa nhẹ vào chiều tối. Trang phục: Giữ ấm nhẹ.",
      estimatedCost: "Trung bình",
      routeMapUrl: "https://www.google.com/maps/dir/Phú+Mỹ,+Bà+Rịa+-+Vũng+Tàu/Trạm+Dừng+Chân+TTC+Phan+Thiết+Vĩnh+Hảo/Chuồn+Chuồn+Bistro+%26+Coffee/Best+Western+Premier+Imperial+Hotel+Dalat/Gà+Nướng+Cơm+Lam+Trên+Đỉnh+Đồi+Trăng/Horizon+Coffee+Đà+Lạt",
      locations: [
        {
          id: "tram-dung-chan-ttc-phan-thiet-vinh-hao",
          order: 1,
          name: "Trạm dừng chân TTC Phan Thiết - Vĩnh Hảo",
          category: "Nghỉ ngơi",
          address: "Tuyến cao tốc Phan Thiết - Vĩnh Hảo, Bình Thuận",
          time: "08:15 - 08:45",
          icon: "fa-coffee",
          coords: [11.0562, 108.2411],
          description: "Điểm dừng chân nghỉ ngơi, ăn sáng nhẹ và giải quyết nhu cầu cá nhân trên tuyến cao tốc mới trước khi rẽ hướng lên Đà Lạt.",
          highlight: "Hiện đại, sạch sẽ, thuận tiện cung đường cao tốc",
          duration: "30 phút",
          cost: "Ăn uống tự chọn",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Tram+dung+chan+TTC+Phan+Thiet+Vinh+Hao"
        },
        {
          id: "kdl-chuon-chuon-bistro-coffee",
          order: 2,
          name: "KDL Chuồn Chuồn Bistro & Coffee",
          category: "Ăn uống",
          address: "Số 292, Thôn 3, Xã Mê Linh, Lâm Hà, Lâm Đồng (Chân đèo Tà Nung)",
          time: "12:00 - 14:15",
          icon: "fa-utensils",
          coords: [11.8956, 108.3314],
          description: "Ăn trưa, thưởng thức cà phê và chụp ảnh thiên nhiên mộc mạc thư giãn giữa đồi núi.",
          highlight: "View đồi chè, thác nước nhân tạo chụp hình siêu đẹp",
          duration: "2 giờ 15 phút",
          cost: "Ăn uống và vé tham quan tự chọn",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Chuon+Chuon+Bistro+Coffee+Da+Lat"
        },
        {
          id: "best-western-premier-imperial-da-lat",
          order: 3,
          name: "Best Western Premier Imperial Đà Lạt",
          category: "Nghỉ ngơi",
          address: "2-4 Đường Trần Phú, Phường 3, Thành phố Đà Lạt, Lâm Đồng",
          time: "15:00 - 17:30",
          icon: "fa-hotel",
          coords: [11.9348, 108.4385],
          description: "Nhận phòng khách sạn, sắp xếp hành lý và nghỉ ngơi hồi phục sức khỏe.",
          highlight: "Khách sạn cao cấp trung tâm thành phố",
          duration: "2 giờ 30 phút",
          cost: "Đã thanh toán phòng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat"
        },
        {
          id: "tren-dinh-doi-trang-ga-nuong",
          order: 4,
          name: "Gà Nướng Cơm Lam Trên Đỉnh Đồi Trăng",
          category: "Ăn uống",
          address: "27K Ngô Thì Sỹ, Phường 4, Thành phố Đà Lạt, Lâm Đồng",
          time: "18:00 - 19:45",
          icon: "fa-bowl-food",
          coords: [11.9333, 108.4255],
          description: "Thưởng thức món gà đồi nướng da giòn dẻo ngọt cùng cơm lam ống tre thơm nồng giữa không gian sân vườn đồi thông thoáng đãng.",
          highlight: "Gà nướng đậm đà hương vị núi rừng Tây Nguyên",
          duration: "1 giờ 45 phút",
          cost: "Theo giá món ăn trên thực đơn",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Ga+Nuong+Com+Lam+Tren+Dinh+Doi+Trang"
        },
        {
          id: "horizon-coffee-da-lat",
          order: 5,
          name: "Cà Phê Horizon Đà Lạt",
          category: "Check-in",
          address: "31/6 Đường 3 Tháng 4, Phường 3, Thành phố Đà Lạt, Lâm Đồng",
          time: "20:00 - 21:30",
          icon: "fa-mug-saucer",
          coords: [11.9205, 108.4485],
          description: "Thưởng thức đồ uống ấm áp và chiêm ngưỡng khu vườn trên mây lung linh ánh đèn hướng thẳng ra thung lũng rừng thông bạt ngàn về đêm.",
          highlight: "Cột đèn check-in độc đáo bao trọn view rừng thông đêm",
          duration: "1 giờ 30 phút",
          cost: "Giá nước từ 60.000 - 100.000 VND",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Horizon+Coffee+Da+Lat"
        }
      ]
    },
    {
      day: 2,
      title: "Vui chơi bung sức & Không gian Acoustic",
      themeColor: "#f97316",
      date: "2026-07-04",
      summary: "Thưởng thức buffet sáng, check-in cà phê Lululola, bung xõa tại Dalat Wonderland, ăn trưa cá tầm bên hồ Tuyền Lâm, ăn tối thịt nướng GoGi và chill Acoustic chợ đêm.",
      center: [11.9100, 108.4300],
      zoom: 12,
      weather: "Ngày nắng ráo thích hợp vận động ngoài trời, tối se lạnh thích hợp nghe nhạc.",
      estimatedCost: "Cao",
      routeMapUrl: "https://www.google.com/maps/dir/Best+Western+Premier+Imperial+Hotel+Dalat/Lululola+Coffee%2B/Dalat+Wonderland/Nhà+hàng+Hồ+Tuyền+Lâm/GoGi+House+Đà+Lạt/Chợ+đêm+Đà+Lạt",
      locations: [
        {
          id: "buffet-sang-khach-san",
          order: 1,
          name: "Thưởng thức buffet sáng tại khách sạn",
          category: "Nghỉ ngơi",
          address: "2-4 Đường Trần Phú, Phường 3, Thành phố Đà Lạt, Lâm Đồng",
          time: "07:30 - 08:15",
          icon: "fa-utensils",
          coords: [11.9348, 108.4385],
          description: "Nạp năng lượng với buffet sáng đa dạng chất lượng tại nhà hàng của khách sạn.",
          highlight: "Không gian sang trọng, món ăn phong phú",
          duration: "45 phút",
          cost: "Bao gồm trong giá phòng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat"
        },
        {
          id: "lululola-coffee",
          order: 2,
          name: "Lululola Coffee+",
          category: "Check-in",
          address: "Đường 3 Tháng 4, Đồi Cà Rốt, Phường 3, Thành phố Đà Lạt, Lâm Đồng",
          time: "08:30 - 09:45",
          icon: "fa-cloud-sun",
          coords: [11.9231, 108.4489],
          description: "Cà phê view mây ngàn, rừng thông nổi tiếng đón nắng sớm bình yên.",
          highlight: "Góc ngắm thung lũng thông reo tuyệt đẹp",
          duration: "1 giờ 15 phút",
          cost: "Giá nước từ 80.000 VND",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Lululola+Coffee+Da+Lat"
        },
        {
          id: "dalat-wonderland",
          order: 3,
          name: "Dalat Wonderland",
          category: "Tham quan",
          address: "Số 19 Đường Hoa Hồng, Khu du lịch Hồ Tuyền Lâm, Phường 4, Thành phố Đà Lạt, Lâm Đồng",
          time: "10:00 - 13:00",
          icon: "fa-jedi",
          coords: [11.8967, 108.4124],
          description: "Bung sức chơi xe địa hình ATV, trải nghiệm trượt tuyết nhà băng; tham quan khu kẹo ngọt đầy màu sắc cho các bé.",
          highlight: "Đa dạng trò chơi cảm giác mạnh và khu chụp ảnh gia đình",
          duration: "3 giờ",
          cost: "Cần mua vé trọn gói",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Dalat+Wonderland+Ho+Tuyen+Lam"
        },
        {
          id: "nha-hang-ho-tuyen-lam",
          order: 4,
          name: "Nhà hàng Hồ Tuyền Lâm",
          category: "Ăn uống",
          address: "Khu du lịch Hồ Tuyền Lâm, Phường 4, Thành phố Đà Lạt, Lâm Đồng",
          time: "13:15 - 14:45",
          icon: "fa-fish",
          coords: [11.8992, 108.4168],
          description: "Thưởng thức bữa trưa với các món đặc sản cá tầm tươi sống bên bờ hồ Tuyền Lâm mát mẻ.",
          highlight: "Cá tầm tươi ngon nguyên con chế biến nhiều món",
          duration: "1 giờ 30 phút",
          cost: "Khoảng 300.000 - 500.000 VND / người",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Nha+hang+Khu+du+lich+Ho+Tuyen+Lam"
        },
        {
          id: "gogi-house-da-lat",
          order: 5,
          name: "GoGi House Đà Lạt",
          category: "Ăn uống",
          address: "Số 11 Đường Trần Quốc Toản, Phường 1, Thành phố Đà Lạt, Lâm Đồng",
          time: "18:00 - 19:45",
          icon: "fa-fire-burner",
          coords: [11.9392, 108.4428],
          description: "Ăn tối thịt nướng Hàn Quốc ấm cúng tại trung tâm phố núi sầm uất.",
          highlight: "Thịt nướng xèo xèo chuẩn vị trong tiết trời lạnh",
          duration: "1 giờ 45 phút",
          cost: "Theo giá menu buffet/gọi món GoGi",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=GoGi+House+Tran+Quoc+Toan+Da+Lat"
        },
        {
          id: "cho-dem-da-lat-acoustic",
          order: 6,
          name: "Chợ đêm Đà Lạt & Thưởng thức Acoustic Live Show",
          category: "Dạo phố",
          address: "Đường Nguyễn Thị Minh Khai, Phường 1, Thành phố Đà Lạt, Lâm Đồng",
          time: "20:00 - 22:00",
          icon: "fa-guitar",
          coords: [11.9424, 108.4377],
          description: "Dạo chợ đêm mua sắm quà lưu niệm, ăn vặt bánh tráng nướng và hòa mình vào đêm nhạc Acoustic live cực chill.",
          highlight: "Âm nhạc sống động hòa trong gió lạnh phố núi",
          duration: "2 giờ",
          cost: "Miễn phí dạo chơi, trả tiền nước/vé nghe nhạc",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Cho+dem+Da+Lat"
        }
      ]
    },
    {
      day: 3,
      title: "Trả phòng - Ăn trưa sinh thái về xuôi",
      themeColor: "#10b981",
      date: "2026-07-05",
      summary: "Thư thả ăn sáng tại khách sạn, check-out và di chuyển về Bảo Lộc ăn trưa đồi chè Đôi Dép trước khi thẳng tiến về Phú Mỹ.",
      center: [11.3000, 107.5000],
      zoom: 9,
      weather: "Nắng ráo cung đường đèo, nhiệt độ tăng dần khi xuống vùng đồng bằng.",
      estimatedCost: "Thấp",
      routeMapUrl: "https://www.google.com/maps/dir/Best+Western+Premier+Imperial+Hotel+Dalat/Cà+phê+Đôi+Dép+Tea+Garden+Bảo+Lộc/Trạm+Dừng+Nghỉ+Cao+Tốc+Long+Thành+Dầu+Giây/Phú+Mỹ,+Bà+Rịa+-+Vũng+Tàu",
      locations: [
        {
          id: "check-out-khach-san",
          order: 1,
          name: "Ăn sáng và làm thủ tục check-out",
          category: "Nghỉ ngơi",
          address: "2-4 Đường Trần Phú, Phường 3, Thành phố Đà Lạt, Lâm Đồng",
          time: "08:00 - 10:00",
          icon: "fa-suitcase",
          coords: [11.9348, 108.4385],
          description: "Thưởng thức buffet sáng chậm rãi và hoàn tất thủ tục trả phòng khách sạn lúc 10:00.",
          highlight: "Thư thả, chuẩn bị hành trình về xuôi",
          duration: "2 giờ",
          cost: "Miễn phí theo phòng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat"
        },
        {
          id: "doi-dep-tea-garden-bao-loc",
          order: 2,
          name: "Cà phê Đôi Dép Tea Garden Bảo Lộc",
          category: "Ăn uống",
          address: "452 Đường Trần Phú, Phường 2, Thành phố Bảo Lộc, Lâm Đồng",
          time: "12:30 - 14:15",
          icon: "fa-leaf",
          coords: [11.4811, 107.8183],
          description: "Không gian sinh thái đồi chè xanh mát tuyệt đẹp, vị trí hoàn hảo để ăn trưa và nghỉ ngơi thư giãn giữa chặng đường về.",
          highlight: "Khuôn viên sinh thái đồi chè rộng lớn, thoáng đãng",
          duration: "1 giờ 45 phút",
          cost: "Ăn uống theo menu nhà hàng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Doi+Dep+Tea+Garden+452+Tran+Phu+Bao+Loc"
        },
        {
          id: "tram-dung-nghi-cao-toc-ve",
          order: 3,
          name: "Trạm dừng nghỉ Cao tốc (Chiều về)",
          category: "Nghỉ ngơi",
          address: "Đường cao tốc Dầu Giây - TP.HCM (đoạn Đồng Nai)",
          time: "16:45 - 17:15",
          icon: "fa-gas-pump",
          coords: [10.9250, 107.1900],
          description: "Điểm nghỉ kỹ thuật chặng cuối trước khi rẽ về lại Phú Mỹ, BRVT.",
          highlight: "Tiện lợi, nhanh chóng",
          duration: "30 phút",
          cost: "Tự túc",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Tram+dung+nghi+Cao+toc+Long+Thanh+Dau+Giay"
        }
      ]
    }
  ],

  notes: [
    "Di chuyển đường đèo Tà Nung và đèo Bảo Lộc cần chú ý tốc độ và giữ khoảng cách an toàn, đặc biệt nếu trời mưa trơn trượt.",
    "Vé tham quan tại Dalat Wonderland nên đặt trước hoặc mua combo để tiết kiệm thời gian xếp hàng.",
    "Chuẩn bị sẵn đồ ấm (áo khoác nhẹ, khăn) cho cả người lớn và trẻ nhỏ vì nhiệt độ Đà Lạt giảm nhanh sau 18:00.",
    "Mang theo giày thể thao hoặc giày bệt để thoải mái tham gia các hoạt động vận động địa hình và đi bộ tại chợ đêm."
  ]
};