window.TRIP_DATA = {
  trip: {
    title: "Đà Lạt tháng 07/2026",
    subtitle: "Lịch trình chuyến đi",
    destination: "Đà Lạt",
    startDate: "2026-07-03",
    endDate: "2026-07-05",
    timezone: "Asia/Ho_Chi_Minh",
    currency: "VND",
    travelers: ["Gia đình Long - Oanh, Hải - Hiền"],
    departure_point: "Phú Mỹ, BRVT",
    coverImage: "",
    hotel: {
      name: "Best Western Premier Imperial Hotel Dalat",
      address: "57-59 Hùng Vương, Phường 9, Thành phố Đà Lạt, Lâm Đồng",
      coords: [11.9442, 108.4687],
      icon: "fa-hotel",
      checkin: "03/07",
      checkout: "05/07",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat+Hung+Vuong"
    },
    transportation: {
      departure: "Xe cá nhân xuất phát từ Phú Mỹ, BRVT lúc 05:30 ngày 03/07/2026",
      local: "Xe cá nhân",
      airportTransfer: "Không sử dụng"
    }
  },

  days: [
    {
      day: 1,
      title: "Hành trình lên Cao Nguyên",
      themeColor: "#2563eb",
      date: "2026-07-03",
      summary: "Khởi hành từ Phú Mỹ qua cao tốc, dừng chân tại trạm TTC Phan Thiết - Vĩnh Hảo, ăn trưa và tham quan sinh thái tại Cao Nguyên Hoa Đà Lạt, nhận phòng khách sạn, tối di chuyển thẳng đến Cafe Dưới Tán Anh Đào kết hợp ăn uống nhẹ và thư giãn.",
      center: [11.5500, 108.1000],
      zoom: 10,
      weatherLocation: "Đà Lạt",
      weatherCoords: [11.9404, 108.4583],
      weather: "03/07: 17,8-21,0°C, mưa phùn/mưa nhỏ; xác suất mưa 97%, lượng mưa khoảng 6 mm. Nên mang áo mưa mỏng, áo khoác nhẹ và giày dễ đi.",
      estimatedCost: "Trung bình",
      routeMapUrl: "https://www.google.com/maps/dir/?api=1&origin=Ph%C3%BA+M%E1%BB%B9,+B%C3%A0+R%E1%BB%8B%E1%BA%A3+-+V%C5%A5ng+T%C3%A0u&destination=Cafe+D%C6%B0%E1%BB%9Bi+T%C3%A1n+Anh+%C4%90%C3%A0o+Nguy%E1%BB%85n+H%E1%BB%AFu+C%E1%BA%A3nh&waypoints=Tr%E1%BA%A1m+D%E1%BB%ABng+Ngh%E1%BB%8B+TTC+V%C4%A9nh+H%E1%BA%A3o+Phan+Thi%E1%BA%BFt%7CKhu+du+l%E1%BB%8Bch+sinh+th%C3%A1i+Cao+Nguy%C3%AAn+Hoa+%C4%90%C3%A0+L%E1%BA%A1t%7CBest+Western+Premier+Imperial+Hotel+Dalat",
      locations: [
        {
          id: "tram-dung-chan-ttc-phan-thiet-vinh-hao",
          order: 1,
          name: "Trạm dừng chân TTC Phan Thiết - Vĩnh Hảo",
          category: "Nghỉ ngơi",
          address: "Km 205+092 Tuyến cao tốc Vĩnh Hảo - Phan Thiết, Hàm Thuận Bắc, Bình Thuận",
          time: "08:15 - 08:45",
          icon: "fa-coffee",
          coords: [11.1215, 108.2844],
          description: "Điểm dừng chân nghỉ ngơi, vệ sinh cá nhân và ăn sáng nhẹ trên tuyến cao tốc trước khi tiếp tục hành trình lên khu vực đèo núi.",
          highlight: "Cơ sở vật chất mới, hiện đại, sạch sẽ và thuận tiện cho lộ trình xe cá nhân",
          duration: "30 phút",
          cost: "Ăn uống tự chọn",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Tram+dung+nghi+TTC+Vinh+Hao+Phan+Thiet"
        },
        {
          id: "cao-nguyen-hoa-da-lat",
          order: 2,
          name: "KDL sinh thái Cao Nguyên Hoa Đà Lạt",
          category: "Tham quan",
          address: "Tiểu khu 158, Đường Đèo Tà Nung, Phường 5, Thành phố Đà Lạt, Lâm Đồng",
          time: "11:45 - 14:30",
          icon: "fa-leaf",
          coords: [11.9482, 108.3846],
          description: "Không gian sinh thái nhiều mảng xanh, đồi thông và vườn hoa. Gia đình có thể ăn trưa nhẹ tại Woody Coffee, nghỉ ngơi, chụp hình và dạo mát trước khi vào trung tâm thành phố.",
          highlight: "Không gian thung lũng xanh, hồ vô cực, quán cà phê gỗ và các góc check-in thiên nhiên",
          duration: "2 giờ 45 phút",
          cost: "Cần mua vé vào cổng (khoảng 150.000đ đã bao gồm nước), ăn uống tự chọn",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Khu+du+lich+sinh+thai+Cao+Nguyen+Hoa+Da+Lat"
        },
        {
          id: "best-western-premier-imperial-da-lat",
          order: 3,
          name: "Best Western Premier Imperial Đà Lạt",
          category: "Nghỉ ngơi",
          address: "57-59 Hùng Vương, Phường 9, Thành phố Đà Lạt, Lâm Đồng",
          time: "15:15 - 17:30",
          icon: "fa-hotel",
          coords: [11.9442, 108.4687],
          description: "Di chuyển về khách sạn, làm thủ tục nhận phòng, sắp xếp hành lý và nghỉ ngơi sau chặng đường dài.",
          highlight: "Khách sạn cao cấp phong cách Đông Dương sang trọng, không gian thoáng đãng",
          duration: "2 giờ 15 phút",
          cost: "Đã thanh toán phòng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat+Hung+Vuong"
        },
        {
          id: "cafe-duoi-tan-anh-dao",
          order: 4,
          name: "Cafe Dưới Tán Anh Đào",
          category: "Ăn uống",
          address: "29B Hùng Vương, Phường 11, Thành phố Đà Lạt, Lâm Đồng",
          time: "18:00 - 21:00",
          icon: "fa-mug-saucer",
          coords: [11.9409, 108.4595],
          description: "Di chuyển thẳng đến quán để kết hợp ăn tối nhẹ với thực đơn tại quán và thư giãn muộn trong không gian sân vườn Natureside. Ánh đèn đêm ấm áp, yên tĩnh giúp gia đình hạ nhịp sau ngày dài di chuyển.",
          highlight: "Tích hợp ăn uống nhẹ, không gian vườn yên tĩnh và vibe Đà Lạt nhẹ nhàng",
          duration: "3 giờ",
          cost: "Chi phí ăn uống và thức uống tự chọn theo menu",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Cafe+Duoi+Tan+Anh+Dao+Natureside+Da+Lat"
        }
      ]
    },
    {
      day: 2,
      title: "Cổ trấn sương sớm & Không gian ven hồ",
      themeColor: "#f97316",
      date: "2026-07-04",
      summary: "Ăn sáng sớm tại khách sạn, đi Lạc Hư Cổ Trấn check-in concept cổ phong hướng Trại Mát - Xuân Trường, tham quan Puppy Farm, ăn trưa sinh thái tại Suối Bình Yên, vui chơi tại Dalat Wonderland, check-in Happy Hill, tối ăn GoGi House và dạo chợ đêm Đà Lạt.",
      center: [11.9300, 108.4550],
      zoom: 11,
      weatherLocation: "Đà Lạt",
      weatherCoords: [11.9404, 108.4583],
      weather: "04/07: 17,6-19,6°C, mưa rào vừa; xác suất mưa 100%, lượng mưa khoảng 14,6 mm. Ưu tiên áo mưa, giày đế bằng và lịch linh hoạt cho các điểm ngoài trời.",
      estimatedCost: "Cao",
      routeMapUrl: "https://www.google.com/maps/dir/?api=1&origin=Best+Western+Premier+Imperial+Hotel+Dalat+Hung+Vuong&destination=Cho+dem+Da+Lat&waypoints=Lac+Hu+Co+Tran+Da+Lat%7CNong+trai+thu+cung+Puppy+Farm%7CKDL+Suoi+Binh+Yen+Tuyen+Lam%7CDalat+Wonderland%7CPhim+truong+Happy+Hill%7CGoGi+House+Bui+Thi+Xuan+Da+Lat",
      locations: [
        {
          id: "buffet-sang-khach-san",
          order: 1,
          name: "Thưởng thức buffet sáng tại khách sạn",
          category: "Nghỉ ngơi",
          address: "57-59 Hùng Vương, Phường 9, Thành phố Đà Lạt, Lâm Đồng",
          time: "07:00 - 07:40",
          icon: "fa-utensils",
          coords: [11.9442, 108.4687],
          description: "Thưởng thức điểm tâm sáng tự chọn tại khách sạn sớm hơn một chút để kịp di chuyển về hướng Trại Mát - Xuân Trường tham quan Lạc Hư Cổ Trấn.",
          highlight: "Bữa sáng tiện lợi, đầy đủ dinh dưỡng khởi động ngày mới đúng giờ",
          duration: "40 phút",
          cost: "Bao gồm trong chi phí phòng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat+Hung+Vuong"
        },
        {
          id: "lac-hu-co-tran",
          order: 2,
          name: "Lạc Hư Cổ Trấn",
          category: "Check-in",
          address: "Đường Lâm Văn Thạnh, khu vực Xuân Trường - Trại Mát, Thành phố Đà Lạt, Lâm Đồng",
          time: "08:20 - 09:45",
          icon: "fa-landmark",
          coords: [11.9448, 108.5156],
          description: "Điểm check-in phong cách cổ trấn Trung Hoa với cổng gỗ, mái ngói, đèn lồng, cầu gỗ, hồ nước và các tiểu cảnh Á Đông. Gia đình có thể chụp ảnh, uống cà phê và tận hưởng không khí sương sớm trên cung đường hướng Trại Mát - Xuân Trường.",
          highlight: "Concept cổ phong khác biệt, nhiều góc ảnh đèn lồng và kiến trúc gỗ rất hợp chụp hình gia đình",
          duration: "1 giờ 25 phút",
          cost: "Cần mua vé vào cổng (đã bao gồm nước), thuê cổ trang tính riêng nếu sử dụng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Lac+Hu+Co+Tran+Da+Lat"
        },
        {
          id: "puppy-farm",
          order: 3,
          name: "Nông trại thú cưng Puppy Farm",
          category: "Tham quan",
          address: "Đường Cam Ly, Phường 7, Thành phố Đà Lạt, Lâm Đồng",
          time: "10:45 - 12:30",
          icon: "fa-paw",
          coords: [11.9612, 108.3978],
          description: "Điểm đến phù hợp cho gia đình và trẻ nhỏ với khu tương tác thú cưng, vườn dâu tây, vườn cà chua công nghệ cao và các khu hoa theo mùa. Thời gian tại Puppy Farm được điều chỉnh để giữ nhịp cho buổi chiều.",
          highlight: "Khu tương tác động vật thân thiện, lạc đà Alpaca, vườn dâu công nghệ cao",
          duration: "1 giờ 45 phút",
          cost: "Cần mua vé tham quan",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Nong+trai+thu+cung+Puppy+Farm+Da+Lat"
        },
        {
          id: "suoi-binh-yen-da-lat",
          order: 4,
          name: "KDL Suối Bình Yên",
          category: "Ăn uống",
          address: "Khu du lịch Hồ Tuyền Lâm, Phường 4, Thành phố Đà Lạt, Lâm Đồng",
          time: "13:15 - 14:15",
          icon: "fa-water",
          coords: [11.8912, 108.4085],
          description: "Di chuyển đến khu vực Hồ Tuyền Lâm để ăn trưa và nghỉ ngơi trong không gian sinh thái ven suối, nhiều cây xanh và không khí mát mẻ.",
          highlight: "Không gian suối tự nhiên yên tĩnh, mộc mạc thích hợp nghỉ ngơi giữa ngày",
          duration: "1 giờ",
          cost: "Chi phí ăn trưa gọi món tự chọn",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=KDL+Suoi+Binh+Yen+Tuyen+Lam"
        },
        {
          id: "dalat-wonderland",
          order: 5,
          name: "KDL Giải Trí Dalat Wonderland",
          category: "Tham quan",
          address: "Số 19 Đường Hoa Hồng, Khu du lịch Hồ Tuyền Lâm, Phường 4, Thành phố Đà Lạt, Lâm Đồng",
          time: "14:30 - 16:10",
          icon: "fa-jedi",
          coords: [11.8967, 108.4124],
          description: "Khu vui chơi giải trí ven hồ Tuyền Lâm với nhiều trò chơi trải nghiệm thú vị, nhà tuyết, vườn chim, đua xe địa hình và không gian check-in lâu đài châu Âu phù hợp cho gia đình.",
          highlight: "Nhiều hoạt động vui chơi giải trí đa dạng thích hợp cho trẻ nhỏ",
          duration: "1 giờ 40 phút",
          cost: "Cần mua vé vào cổng / trọn gói",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Dalat+Wonderland+Hoa+Hong"
        },
        {
          id: "happy-hill-tuyen-lam",
          order: 6,
          name: "Phim trường sinh thái Happy Hill",
          category: "Check-in",
          address: "Khu du lịch Hồ Tuyền Lâm, Phường 4, Thành phố Đà Lạt, Lâm Đồng",
          time: "16:20 - 17:00",
          icon: "fa-camera",
          coords: [11.8898, 108.4145],
          description: "Ghé phim trường ven hồ để chụp ảnh chiều muộn, ngắm cảnh trọn vẹn góc Hồ Tuyền Lâm thơ mộng khi hoàng hôn buông xuống.",
          highlight: "View Hồ Tuyền Lâm đắt giá, nhiều tiểu cảnh hoa, cầu gỗ sát mặt nước",
          duration: "40 phút",
          cost: "Cần mua vé vào cổng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Phim+truong+Happy+Hill+Tuyen+Lam"
        },
        {
          id: "gogi-house-da-lat",
          order: 7,
          name: "GoGi House Đà Lạt",
          category: "Ăn uống",
          address: "Số 152 Bùi Thị Xuân, Phường 2, Thành phố Đà Lạt, Lâm Đồng",
          time: "18:00 - 19:45",
          icon: "fa-fire-burner",
          coords: [11.9478, 108.4412],
          description: "Bữa tối thịt nướng Hàn Quốc ấm cúng tại chi nhánh Bùi Thị Xuân, phù hợp để nạp lại năng lượng sau một ngày dài di chuyển ngoài trời.",
          highlight: "Hương vị thịt nướng chuẩn Hàn, không gian ấm cúng, dịch vụ chu đáo",
          duration: "1 giờ 45 phút",
          cost: "Ăn uống gọi món hoặc buffet theo menu",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=GoGi+House+Bui+Thi+Xuan+Da+Lat"
        },
        {
          id: "cho-dem-da-lat",
          order: 8,
          name: "Chợ đêm Đà Lạt",
          category: "Dạo phố",
          address: "Đường Nguyễn Thị Minh Khai, Phường 1, Thành phố Đà Lạt, Lâm Đồng",
          time: "20:00 - 22:00",
          icon: "fa-bag-shopping",
          coords: [11.9424, 108.4377],
          description: "Dạo chơi không khí phố núi nhộn nhịp, mua quà lưu niệm, mứt dâu và thưởng thức các món ăn vặt nóng hổi như bánh tráng nướng, sữa đậu nành.",
          highlight: "Không khí phố núi đặc trưng sầm uất, thiên đường đồ ăn vặt",
          duration: "2 giờ",
          cost: "Tự túc ăn vặt và mua sắm cá nhân",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Cho+dem+Da+Lat"
        }
      ]
    },
    {
      day: 3,
      title: "Trả phòng - Thưởng trà sinh thái về lại xuôi",
      themeColor: "#10b981",
      date: "2026-07-05",
      summary: "Thư thả ăn sáng, trả phòng khách sạn, di chuyển xuống Bảo Lộc tham quan đồi chè và ăn trưa tại Vườn trà Vinh An Oolong trước khi về lại Phú Mỹ.",
      center: [11.3000, 107.5000],
      zoom: 9,
      weatherLocation: "Bảo Lộc",
      weatherCoords: [11.5480, 107.8077],
      weather: "05/07: 20,2-25,3°C, mưa phùn/mưa nhỏ; xác suất mưa 90%, lượng mưa khoảng 11,5 mm. Cần kiểm tra phanh, xăng và chạy chậm nếu đường đèo ẩm.",
      estimatedCost: "Thấp",
      routeMapUrl: "https://www.google.com/maps/dir/?api=1&origin=Best+Western+Premier+Imperial+Hotel+Dalat+Hung+Vuong&destination=Ph%C3%BA+M%E1%BB%B9,+B%C3%A0+R%E1%BB%8B%E1%BA%A3+-+V%C5%A5ng+T%C3%A0u&waypoints=Vuon+tra+Vinh+An+Oolong+Tea+Bao+Loc",
      locations: [
        {
          id: "check-out-khach-san",
          order: 1,
          name: "Ăn sáng và làm thủ tục check-out khách sạn",
          category: "Nghỉ ngơi",
          address: "57-59 Hùng Vương, Phường 9, Thành phố Đà Lạt, Lâm Đồng",
          time: "08:00 - 10:00",
          icon: "fa-suitcase",
          coords: [11.9442, 108.4687],
          description: "Dành thời gian ăn sáng thong thả, kiểm tra kỹ hành lý và hoàn tất thủ tục trả phòng trước khi xuất phát rời Đà Lạt.",
          highlight: "Khởi hành ngày cuối nhẹ nhàng, tránh vội vàng trước chặng đường dài",
          duration: "2 giờ",
          cost: "Bao gồm trong gói phòng",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Best+Western+Premier+Imperial+Hotel+Dalat+Hung+Vuong"
        },
        {
          id: "vuon-tra-vinh-an-oolong",
          order: 2,
          name: "Vườn trà Vinh An Oolong Tea",
          category: "Ăn uống",
          address: "Thôn 4, Xã Đại Lào, Thành phố Bảo Lộc, Lâm Đồng",
          time: "12:30 - 14:30",
          icon: "fa-leaf",
          coords: [11.4752, 107.8211],
          description: "Dừng chân tại không gian nông trường đồi chè ô long xanh ngắt ở Bảo Lộc, kết hợp nghỉ chân ăn trưa, thưởng thức trà nóng đặc sản và thư giãn giữa chặng đường về.",
          highlight: "Cảnh sắc nông trường trà xanh mát, không gian thoáng đãng giúp hồi phục tinh thần lái xe",
          duration: "2 giờ",
          cost: "Chi phí ăn uống và thưởng trà theo menu thực tế",
          mapUrl: "https://www.google.com/maps/search/?api=1&query=Vuon+tra+Vinh+An+Oolong+Tea+Bao+Loc"
        }
      ]
    }
  ],

  notes: [
    "Ngày 1 là ngày di chuyển dài từ Phú Mỹ lên Đà Lạt. Lịch trình tối đã lược bỏ quán ăn riêng để đi thẳng đến Cafe Dưới Tán Anh Đào kết hợp ăn nhẹ tại chỗ, giúp giảm bớt việc di chuyển liên tục.",
    "Khách sạn Best Western Premier Imperial nằm trên đường Hùng Vương (khu vực Trại Mát/Phường 9) thay vì địa chỉ cũ ở Trần Phú, giao thông rộng rãi và thông thoáng.",
    "Cafe Dưới Tán Anh Đào phù hợp buổi tối nhờ không gian sân vườn, ánh đèn ấm và vibe thư giãn; tháng 7 không phải mùa mai anh đào nên không đặt kỳ vọng ngắm hoa nở rộ.",
    "Lạc Hư Cổ Trấn thay Morning in Town Cafe ở sáng ngày 2; điểm này nằm hướng Trại Mát - Xuân Trường (cùng trục đường Hùng Vương của khách sạn), rất tiện di chuyển nếu xuất phát sớm.",
    "Lạc Hư Cổ Trấn có concept cổ phong, nhiều tiểu cảnh gỗ, đá, cầu, hồ và đèn lồng; nên mang giày đế bằng, tránh giày cao gót nếu muốn chụp ảnh thoải mái.",
    "Ngày 2 là ngày nhiều hoạt động và có quãng di chuyển chéo hướng Đông - Tây; nếu trời mưa hoặc gia đình mệt, nên rút ngắn Happy Hill hoặc Dalat Wonderland.",
    "Cụm Hồ Tuyền Lâm có nhiều đoạn đường dốc, cong và có thể ẩm trơn khi mưa; xe cá nhân nên di chuyển chậm và tránh chạy sát giờ tối.",
    "Nhiệt độ Đà Lạt sau 18:00 giảm nhanh, nên chuẩn bị áo khoác nhẹ cho cả người lớn và trẻ nhỏ.",
    "Các điểm sinh thái như Cao Nguyên Hoa, Suối Bình Yên, Happy Hill có thể có nền đất, đá hoặc cỏ ẩm; nên mang giày thể thao hoặc giày bệt dễ đi.",
    "Trước ngày đi nên kiểm tra lại giờ mở cửa, giá vé và tình trạng hoạt động thực tế của các điểm tham quan vì lịch vận hành có thể thay đổi theo thời tiết hoặc mùa cao điểm."
  ]
};
